# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a23cdb1f4e9b42aac0ce6d3ed4b58d59feed5a2b1ab670009dbeafee9d49d616d00bdccc12844ee2122dde41dd8e8747acdcddd1d6b2d864dadd9472cc7cb025

test:
  secret_key_base: 2ef84f601dc3e3b1b50f425d074547684245b1b666a45bf956673a6d4fb285b5cbfa0c2cb8dea71325fff429c0973c4f5ed22e07d82264e5eeff2934929502c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
