# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fa124976b1b02e690f75a61b284804456be5beb3bf1252521f0e45bb4670e71d0dc339e5a46803d5204d73e51d9688db39f48530488410e1c229c7a48d339b8

test:
  secret_key_base: b7b333a699c3a71c9e5cced4b019cbfb6c3d7f23356cbea414d481653688ca5c397dc631269508acea4ddc2fd3ec3cddeb3c25856efb983956c468d9404a8ed6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
