# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19866eee8c788799c21361bb9fb966dabd80b06e6b07f604e1dd013f97353cdef0b3088915370177cfffbf028ed287e202e595c8d9bccb9eba042d44fedf5fd6

test:
  secret_key_base: 33e0574ada96c3b46ba082ab352e747feb4d425063a492d1953b4521bd7890a1805d7b63977cc02b817676f126d492ffcf57bd90b9f32041adc937ee40915105

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
