# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91d1b7e96a0a951163b378269563024d19344080181b100a27d58017232085afdebf676a96a7c4b194e58572de5a52a2542b8e314d8dd8425ec4fe0c41565440

test:
  secret_key_base: b15fdb4dccba25af29484893bb337bbfbfad0678a9e42a5bc44f847e75fc2dbdf1b7c9b0b6a9dc03982deccd0c8c8cdb3dd04a9220cb9eb6ea3a7498c22c3d8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
