# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb5fcb3548eeaa402da04e0da30f260e420ab08311c2784f45219ac510f46515223f49a67d71119e8294dd7ed1669fbe332400525f19cfdd9bf99227bdcc1e2d

test:
  secret_key_base: 876b43f157d2d0494c5698d57b4365a76a92a4ec0f650950936037e7b9f995b79920fe7b95db104f3653727745fe71ba627eecb01cd9efe2d0c41b92b0784e40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
