# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7b8e4ee5e8563374e1e20b098300af26ce0917eee89759846d5804dd553a0d76d3d12da0048bb42c268a936cb22861f37117b9a962e234b0c6c0e8380a4f532

test:
  secret_key_base: 9a9fd4354558c6ded641f493bd045ec35bbb36e116a7a80172f4560332f72e749705ba3cb42e38b109e81f4a20e277e303adaf0bc9eba05f51601ebd93536a59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
