# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc45a97b7075e4dc10ac1e53b67eb2ca2217043a801a35e2c4d9de8bf74c67c8fcfce9474c152b3c8a38e037c7684bc47c21bcc6760450e84e724c8145fcc3cc

test:
  secret_key_base: 666380ca85a5ebcb5c9592a94a45466bdf6b6c6c3f4cbd2276d3ce06078f8fb3848bc039184e98e39458fb7a8d8e70b5bae92a93295f97b3fa0aa7ad9c9c5952

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
